#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)" >&2
   exit 1
fi

cd ..
git clone https://github.com/Rrominet/cpp-utils
cd ./cpp-utils
chmod +x ./build-n-install
./build-n-install
cd ../fxos_gui-lib
mkdir -p ./build

apt install -y libgtkmm-4.0-dev pkg-config
cd ./build
chmod +x ../make
chmod +x ../install
../make gtk shared release libs="../../cpp-utils_dependencies" fm="../../cpp-utils"
../install
