#!/usr/bin/env python3
import sys
import os

if (sys.argv[1] == "shared") :
    if os.path.exists("/usr/local/lib/libmlgui.so") :
        os.remove("/usr/local/lib/libmlgui.so")
        print ("Old installation removed.")
    os.system("mkdir -p /opt/mlgui")
    os.system("mkdir -p /opt/mlgui/lib")
    os.system("mkdir -p /opt/mlgui/data")
    os.system("cp libmlgui.so /opt/mlgui/lib/libmlgui.so")
    os.system("cp *.css /opt/mlgui/data/")
    os.system("cp -r images /opt/mlgui/data/")
    os.system("ln -s /opt/mlgui/lib/libmlgui.so /usr/local/lib/libmlgui.so")
    print ("libmlgui.so installed in /opt/mlgui/lib/libmlgui.so and smylink to /usr/local/lib/libmlgui.so")
    exit()
