#!/usr/bin/env python3
import sys
import os

if (sys.argv[1] == "shared") :
    if os.path.exists("/usr/local/lib/libmlgui.so") :
        os.remove("/usr/local/lib/libmlgui.so")
        print ("Old installation removed.")
    os.system("mkdir -p /opt/mlgui")
    os.system("mkdir -p /opt/mlgui/lib")
    os.system("mkdir -p /opt/mlgui/data")
    os.system("cp -v libmlgui.so /opt/mlgui/lib/libmlgui.so")
    os.system("cp -v version /opt/mlgui/lib/version")
    os.system("cp -v dependencies /opt/mlgui/lib/dependencies")
    os.system("cp -v *.css /opt/mlgui/data/")
    os.system("cp -vr images /opt/mlgui/data/")
    os.system("chmod 777 -R /opt/mlgui")
    print ("libmlgui.so installed in /opt/mlgui/lib/libmlgui.so")
    exit()
