//This is a generated file, don't change it manually, it will be override when rebuild.

ml::Vec<std::function<void (EventInfos&)>> _click;
bool _click_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _double_click;
bool _double_click_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _mouse_enter;
bool _mouse_enter_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _mouse_leave;
bool _mouse_leave_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _mouse_move;
bool _mouse_move_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _mouse_up;
bool _mouse_up_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _mouse_down;
bool _mouse_down_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _left_up;
bool _left_up_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _left_down;
bool _left_down_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _right_up;
bool _right_up_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _right_down;
bool _right_down_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _middle_up;
bool _middle_up_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _middle_down;
bool _middle_down_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _key_down;
bool _key_down_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _key_up;
bool _key_up_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _wheel;
bool _wheel_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _focus;
bool _focus_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _unfocus;
bool _unfocus_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _change;
bool _change_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _valid;
bool _valid_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _shown;
bool _shown_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _hidden;
bool _hidden_initialized = false;
ml::Vec<std::function<void (EventInfos&)>> _resize;
bool _resize_initialized = false;
