//This is a generated file, don't change it manually, it will be override when rebuild.

std::shared_ptr<ml::Box> createBox();
std::shared_ptr<ml::Box> createBox(ml::Box* parent);
std::shared_ptr<ml::Box> createBox(ml::Scrollable* parent);
std::shared_ptr<ml::Box> createBox(ml::Popover* parent);
std::shared_ptr<ml::Box> createBox(ml::AbsoluteBox* parent);
std::shared_ptr<ml::Box> createBox(ml::Fixed* parent);
std::shared_ptr<ml::Box> createBox(ml::Window* parent);

std::shared_ptr<ml::Scrollable> createScrollable();
std::shared_ptr<ml::Scrollable> createScrollable(ml::Box* parent);
std::shared_ptr<ml::Scrollable> createScrollable(ml::Scrollable* parent);
std::shared_ptr<ml::Scrollable> createScrollable(ml::Popover* parent);
std::shared_ptr<ml::Scrollable> createScrollable(ml::AbsoluteBox* parent);
std::shared_ptr<ml::Scrollable> createScrollable(ml::Fixed* parent);
std::shared_ptr<ml::Scrollable> createScrollable(ml::Window* parent);

std::shared_ptr<ml::Popover> createPopover();
std::shared_ptr<ml::Popover> createPopover(ml::Box* parent);
std::shared_ptr<ml::Popover> createPopover(ml::Scrollable* parent);
std::shared_ptr<ml::Popover> createPopover(ml::Popover* parent);
std::shared_ptr<ml::Popover> createPopover(ml::AbsoluteBox* parent);
std::shared_ptr<ml::Popover> createPopover(ml::Fixed* parent);
std::shared_ptr<ml::Popover> createPopover(ml::Window* parent);

std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox();
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::Box* parent);
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::Scrollable* parent);
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::Popover* parent);
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::AbsoluteBox* parent);
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::Fixed* parent);
std::shared_ptr<ml::AbsoluteBox> createAbsoluteBox(ml::Window* parent);

std::shared_ptr<ml::Fixed> createFixed();
std::shared_ptr<ml::Fixed> createFixed(ml::Box* parent);
std::shared_ptr<ml::Fixed> createFixed(ml::Scrollable* parent);
std::shared_ptr<ml::Fixed> createFixed(ml::Popover* parent);
std::shared_ptr<ml::Fixed> createFixed(ml::AbsoluteBox* parent);
std::shared_ptr<ml::Fixed> createFixed(ml::Fixed* parent);
std::shared_ptr<ml::Fixed> createFixed(ml::Window* parent);


std::shared_ptr<ml::Button> createButton();
std::shared_ptr<ml::Button> createButton(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Button> createButton(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Button> createButton(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Button> createButton(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Button> createButton(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::ToggleButton> createToggleButton();
std::shared_ptr<ml::ToggleButton> createToggleButton(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::ToggleButton> createToggleButton(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::ToggleButton> createToggleButton(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::ToggleButton> createToggleButton(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::ToggleButton> createToggleButton(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Switch> createSwitch();
std::shared_ptr<ml::Switch> createSwitch(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Switch> createSwitch(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Switch> createSwitch(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Switch> createSwitch(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Switch> createSwitch(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::CheckBox> createCheckBox();
std::shared_ptr<ml::CheckBox> createCheckBox(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::CheckBox> createCheckBox(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::CheckBox> createCheckBox(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::CheckBox> createCheckBox(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::CheckBox> createCheckBox(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::ProgressBar> createProgressBar();
std::shared_ptr<ml::ProgressBar> createProgressBar(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::ProgressBar> createProgressBar(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::ProgressBar> createProgressBar(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::ProgressBar> createProgressBar(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::ProgressBar> createProgressBar(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Entry> createEntry();
std::shared_ptr<ml::Entry> createEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Entry> createEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Entry> createEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Entry> createEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Entry> createEntry(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::PasswordEntry> createPasswordEntry();
std::shared_ptr<ml::PasswordEntry> createPasswordEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::PasswordEntry> createPasswordEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::PasswordEntry> createPasswordEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::PasswordEntry> createPasswordEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::PasswordEntry> createPasswordEntry(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::SpinButton> createSpinButton();
std::shared_ptr<ml::SpinButton> createSpinButton(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::SpinButton> createSpinButton(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::SpinButton> createSpinButton(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::SpinButton> createSpinButton(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::SpinButton> createSpinButton(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Slider> createSlider();
std::shared_ptr<ml::Slider> createSlider(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Slider> createSlider(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Slider> createSlider(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Slider> createSlider(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Slider> createSlider(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Label> createLabel();
std::shared_ptr<ml::Label> createLabel(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Label> createLabel(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Label> createLabel(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Label> createLabel(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Label> createLabel(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Spinner> createSpinner();
std::shared_ptr<ml::Spinner> createSpinner(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Spinner> createSpinner(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Spinner> createSpinner(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Spinner> createSpinner(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Spinner> createSpinner(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::Image> createImage();
std::shared_ptr<ml::Image> createImage(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::Image> createImage(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::Image> createImage(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::Image> createImage(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::Image> createImage(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::MultilineEntry> createMultilineEntry();
std::shared_ptr<ml::MultilineEntry> createMultilineEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::MultilineEntry> createMultilineEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::MultilineEntry> createMultilineEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::MultilineEntry> createMultilineEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::MultilineEntry> createMultilineEntry(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::WebView> createWebView();
std::shared_ptr<ml::WebView> createWebView(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::WebView> createWebView(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::WebView> createWebView(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::WebView> createWebView(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::WebView> createWebView(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::DateEntry> createDateEntry();
std::shared_ptr<ml::DateEntry> createDateEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::DateEntry> createDateEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::DateEntry> createDateEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::DateEntry> createDateEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::DateEntry> createDateEntry(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::TimeEntry> createTimeEntry();
std::shared_ptr<ml::TimeEntry> createTimeEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::TimeEntry> createTimeEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::TimeEntry> createTimeEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::TimeEntry> createTimeEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::TimeEntry> createTimeEntry(ml::Fixed * parent, const std::string& text = "");
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry();
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry(ml::Box * parent, const std::string& text = "");
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry(ml::Scrollable * parent, const std::string& text = "");
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry(ml::Popover * parent, const std::string& text = "");
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry(ml::AbsoluteBox * parent, const std::string& text = "");
std::shared_ptr<ml::DateTimeEntry> createDateTimeEntry(ml::Fixed * parent, const std::string& text = "");
